api/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^home/', views.apihome, name='api_home'),
    url(r'^report', views.report),
    url(r'^$', views.apihome, name='api_home'),
    url(r'^project(?P<projectId>[a-z,A-Z,{,},.,0-9,:,%,-]+)/$', views.apilist, name="api_list"),
    url(r'^project(?P<projectId>[a-z,A-Z,{,},.,0-9,:,%,-]+)/config/$', views.project_config, name="project_config"),
    url(r'^project(?P<projectId>[a-z,A-Z,{,},.,0-9,:,%,-]+)/api(?P<apiId>[a-z,A-Z,{,},.,0-9,:,%,-]+)/doc/$', views.api_doc, name="api_doc"),
    url(r'^project(?P<projectId>[a-z,A-Z,{,},.,0-9,:,%,-]+)/api(?P<apiId>[a-z,A-Z,{,},.,0-9,:,%,-]+)/debug/$', views.api_debug, name="api_debug"),
    url(r'^project(?P<projectId>[a-z,A-Z,{,},.,0-9,:,%,-]+)/api(?P<apiId>[a-z,A-Z,{,},.,0-9,:,%,-]+)/test/(?P<envId>[a-z,A-Z,{,},.,0-9,:,%,-]+)$', views.api_test, name="api_test"),
]

api/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime

# Create your models here.


TYPE_CHOICE = (("str", "str"),
               ("int", "int"),)

class project(models.Model):
    name = models.CharField(max_length=100)
    host = models.CharField(max_length=100)
    port = models.CharField(max_length=10)


class env(models.Model):
    projectId = models.ForeignKey(project, on_delete=models.CASCADE)
    envName = models.CharField(max_length=100)
    envHost = models.CharField(max_length=100)
    envPort = models.CharField(max_length=100, default='80')
    envHeaders = models.CharField(max_length=1000, default='{}')
    default = models.BooleanField(default=False)


class apiList(models.Model):
    projectName = models.ForeignKey(project, on_delete=models.CASCADE)
    apiName = models.CharField(max_length=100)
    url = models.CharField(max_length=100)
    request_method = models.CharField(max_length=100)
    creater = models.CharField(max_length=100)
    request_protocol = models.CharField(max_length=100, default="http")
    env = models.CharField(max_length=100, default="Online")
    post_method = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return self.apiName


class ApiDetail(models.Model):

    apiId = models.ForeignKey(apiList, on_delete=models.CASCADE)
    debug_sample = models.CharField(max_length=1000, blank=True, null=True)


class ApiParams(models.Model):
    apiId = models.ForeignKey(apiList, on_delete=models.CASCADE)
    key = models.CharField(max_length=1000, null=True)
    key_type = models.CharField(max_length=1000, choices=TYPE_CHOICE, default="str")
    key_must = models.BooleanField(default=True)
    key_default = models.CharField(max_length=1000, null=True, blank=True)
    key_description = models.CharField(max_length=1000, null=True, blank=True)
    key_value = models.CharField(max_length=1000, null=True, blank=True)
    key_selected = models.BooleanField(default=False)

    def __str__(self):
        return str(self.apiId)


class ApiBody(models.Model):
    apiId = models.ForeignKey(apiList, on_delete=models.CASCADE)
    body = models.CharField(max_length=1000, null=True)
    body_type = models.CharField(max_length=1000, choices=TYPE_CHOICE, default="str")
    body_must = models.BooleanField(default=True)
    body_default = models.CharField(max_length=1000, null=True, blank=True)
    body_description = models.CharField(max_length=1000, null=True, blank=True)
    body_value = models.CharField(max_length=1000, null=True, blank=True)
    body_selected = models.BooleanField(default=False)

    def __str__(self):
        return str(self.apiId)


class ApiDebug(models.Model):
    apiId = models.ForeignKey(apiList, on_delete=models.CASCADE)
    apiHead = models.CharField(max_length=1000, blank=True, null=True)
    apiParams = models.CharField(max_length=1000, blank=True, null=True)
    apiBodys = models.CharField(max_length=1000, blank=True, null=True)
    createTime = models.DateTimeField("createTime", default=datetime.now)


class ApiTest(models.Model):
    apiId = models.ForeignKey(apiList, on_delete=models.CASCADE)
    env = models.ForeignKey(env, on_delete=models.CASCADE)
    TestHead = models.CharField(max_length=1000, blank=True, null=True)
    TestParams = models.CharField(max_length=1000, blank=True, null=True)
    TestParams_type = models.CharField(max_length=1000, blank=True, null=True, default='{}')
    TestBodys = models.CharField(max_length=1000, blank=True, null=True)
    TestBodys_type = models.CharField(max_length=1000, blank=True, null=True, default='{}')
    Response_code = models.CharField(max_length=10, blank=True, null=True)
    Response_time = models.CharField(max_length=100, blank=True, null=True)
    Response_content = models.TextField(blank=True, null=True)
    Except_code = models.CharField(max_length=10, blank=True, null=True)
    Except_time = models.CharField(max_length=100, blank=True, null=True)
    Except_content = models.CharField(max_length=1000, blank=True, null=True)
    CaseNum = models.CharField(max_length=1000, blank=True, null=True)
    Judge_logic = models.CharField(max_length=1000, blank=True, null=True)
    Judge_type = models.CharField(max_length=1000, blank=True, null=True)
    Judge_result = models.CharField(max_length=1000, default='{}')


class ApiTestResultKey(models.Model):
    apiId = models.ForeignKey(apiList, on_delete=models.CASCADE)
    Result_key = models.CharField(max_length=1000, blank=True, null=True)
    Result_key_type = models.CharField(max_length=1000, blank=True, null=True)


class ApiScript(models.Model):
    apiId = models.ForeignKey(apiList, on_delete=models.CASCADE)
    ScriptName = models.CharField(max_length=100, blank=True, null=True)
    ScriptTpye = models.CharField(max_length=100, blank=True, null=True)
    ScriptFile = models.FileField(upload_to='./api/upload')
    createTime = models.DateTimeField("createTime", default=datetime.now)
    updateTime = models.DateTimeField("updateTime", default=datetime.now)
    author = models.CharField(max_length=100, blank=True, null=True)

api/templates/apibase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous">
    </script>
    {% load staticfiles %}
    {% block head_script %}
    {% endblock %}
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <title>什么值得买</title>

    <style>
        li {display: inline}
    </style>
</head>
<body role="document">
<!--导航栏-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/index/">测试工具平台</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-right navbar-nav">
                <li><a href="#">{{ user }}</a> </li>
                <li><a href="/logout/">退出</a> </li>
            </ul>
        </div>
    </div>

</nav>

<!--功能列表-->
<div>
    <ol class="breadcrumb" style="padding-top: 60px; padding-left: 200px; position: fixed; width: 100%; z-index: 999;">
        <li><a href="/index/">首页</a></li>
        {% block breadcrumb_button %}
        {% endblock %}
    </ol>

</div>

<div style="padding-top: 120px"></div>

{% block api_home_content %}


{% endblock %}
{% if messages %}
<script>
    {% for msg in messages %}
        alert('{{ msg.message }}');
    {% endfor %}
</script>
{% endif %}

</body>
</html>

api/templates/apidebug.html
{% extends 'apibase.html' %}


{% block head_script %}
	<link href="{{ STATIC_URL }}css/jsonTree.css" rel="stylesheet">
    <script src="{{ STATIC_URL }}js/jsonTree.js"></script>

{% endblock %}

{% block breadcrumb_button %}
    <li><a href="{% url 'api_home' %}">接口平台</a></li>
    <li ><a href="/api/project{{ project_obj.id }}">{{ project_obj.name }}</a></li>
    <li class="active">{{ api_obj.apiName }}</li>
    <a href="/api/project{{ project_obj.id }}/api{{ api_obj.id }}/test/{{ env_default }}" class="btn btn-default btn-xs " role="button" style="float: right; margin-right: 150px">测试</a>
    <a href="/api/project{{ project_obj.id }}/api{{ api_obj.id }}/debug" class="btn btn-primary btn-xs " role="button" style="float: right; margin-right: 10px">调试</a>
    <a href="/api/project{{ project_obj.id }}/api{{ api_obj.id }}/doc" class="btn btn-default btn-xs " role="button" style="float: right; margin-right: 10px">文档</a>
{% endblock %}

{% block api_home_content %}


<div class="container">
<form method="post" action="" class="form-horizontal">
    {% csrf_token %}

    <div class="form-group">


        <div class="col-sm-1 col-sm-offset-1">{{ debugEnv.env }}</div>




        <div class="col-sm-7">
            <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">{{ api_obj.request_method }}</span>
            <input type="text" class="form-control col-sm-4 " aria-activedescendant="basic-addon1" value="{{ api_obj.request_protocol }}://{{ project_obj.host }}:{{ project_obj.port }}{{ api_obj.url }}" readonly="readonly" style="background-color: white">
            </div>
        </div>

        <input class="btn btn-primary col-sm-1 " type="submit" value="DEBUG" name="debug" id="debug">
    </div>


    <div class="form-group">
        <div class="row">
        <div class="btn-group col-sm-2 col-sm-offset-1">
              <button type="button" class="btn btn-info btn-xs">Headers</button>
              <button type="button" class="btn btn-info dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
        </div>
        </div>
    </div>


    <div class="form-group">
        <div class="row">
            <div class="btn-group col-sm-2 col-sm-offset-1">
                  <button type="button" class="btn btn-info btn-xs">Params</button>
                  <button type="button" class="btn btn-info dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                  </button>
            </div>
        </div>

            <div  style="margin-top: 10px">
                {{ CustomApiParamsInlineForm.management_form }}
                {% for item in CustomApiParamsInlineForm %}
                    <div class="row">
                        {{ item.id }}
                        <div class="col-sm-1 col-sm-offset-1 control-label">{{ item.key_value.label }}:</div>
                        <div class="col-sm-5">{{ item.key_value }}</div>

                        <div hidden>

                            {{ item.key }}
                        </div>
                    </div>

                {% endfor %}
            </div>

    </div>

    <div class="form-group">
        <div class="row">
        <div class="btn-group col-sm-2 col-sm-offset-1">
              <button type="button" class="btn btn-info btn-xs">Bodys</button>
              <button type="button" class="btn btn-info dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
        </div>
        </div>

        <div  style="margin-top: 10px">
                {{ CustomApiBodyInlineForm.management_form }}
                {% for item in CustomApiBodyInlineForm %}
                    <div class="row">
                        {{ item.id }}
                        <div class="col-sm-1 col-sm-offset-1 control-label">{{ item.body_value.label }}:</div>
                        <div class="col-sm-5">{{ item.body_value }}</div>

                        <div hidden>

                            {{ item.body }}
                        </div>
                    </div>

                {% endfor %}
            </div>
    </div>
</form>

<div class="col-sm-2 ">
<h4>Response_content</h4>

</div>
<div class="col-sm-2">
    <input type="button" class="btn btn-primary btn-xs" value="全部展开" onclick="treeexpand()">
</div>

    <div id="wrapper" class="col-sm-12">

    </div>

</div>

    <script>
            // Get DOM-element for inserting json-tree
            var wrapper = document.getElementById("wrapper");

            // Get json-data by javascript-object
            var data = {
            };

            // or from a string by JSON.parse(str) method
            console.log({{ response_data|safe }})
            var dataStr = {{ response_data|safe }};
            dataStr = JSON.stringify(dataStr);
            console.log(dataStr)
            try {
                var data = JSON.parse(dataStr);
            } catch (e) {}

            // Create json-tree
            var tree = jsonTree.create(data, wrapper);

            // Expand all (or selected) child nodes of root (optional)
            tree.expand(function(node) {
               return node.childNodes.length < 2 || node.label === 'phoneNumbers';
            })

            function treeexpand() {
                tree.expand()
            }

    </script>


{% endblock %}

api/templates/apihome.html
{% extends 'apibase.html' %}
{% block breadcrumb_button %}
    <li class="active">接口平台</li>
    <input class="btn btn-primary btn-xs" type="button" value="添加新项目" style="display: inline;float: right;
    margin-right: 200px" onclick="displayCreate()">
    <input class="btn btn-primary btn-xs" type="button" value="编辑项目" style="float: right; margin-right: 10px"
           onclick="editDate()">
{% endblock %}
{% block api_home_content %}


<div class="container" id="editbefore">
    <table border="1" class="table table-striped table-bordered table-hover table-condensed table-responsive">
        <tr>
            <td>项目名</td>
            <td>url</td>
            <td></td>
        </tr>
        {% for form in project_modelforset %}
            <tr>
                <td><a href="/api/project{{  form.id.value  }}">{{ form.name.value}}</a></td>
                <td>{{ form.host.value}}:{{ form.port.value}}</td>
                <td><a href="/api/project{{  form.id.value  }}/config">项目配置</a> </td>
            </tr>
        {% endfor %}
    </table>
</div>


<div class="container" id="editafter" style="display: none">
    <form method="post" action="">{% csrf_token %}
    <table border="1" class="table table-striped table-bordered table-hover table-condensed table-responsive">
        <tr>
            <td>项目名</td>
            <td>url</td>
            <td>port</td>
            <td>删除</td>
        </tr>

        {{ project_modelforset.management_form }}
        {% for form in project_modelforset %}
            <tr>
                {{  form.id }}
                <td>{{ form.name}}</td>
                <td>{{ form.host}}</td>
                <td>{{ form.port }}</td>
                <td>{{ form.DELETE }}</td>
            </tr>
        {% endfor %}



    </table>
        <input class="btn btn-primary btn-xs" type="submit" value="保存" name="editsave" style="float: right; margin-right: 10px">
    </form>
</div>

    <div id="createProject" style="width: 100%; height: 100%; background-color: rgba(0,0,0,0.3); position: fixed;
    top: 0; left: 0; display: none; justify-content: center; align-content: center; align-items: center;
    z-index: 9999;">
        <div style="border-radius: 5px; background-color: #fff; max-width: 600px; min-width: 200px; padding: 30px 20px;" ／
        class="container">
            <form method="post" action="" class="form-horizontal">
                <h3 style="text-align: center">添加新项目</h3>
                <div class="form-group" style="margin-top: 40px">
                    <label class="col-sm-3 control-label">项目名:</label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" id="id_name" name="name">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">host:</label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" id="id_host" name="host">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">port:</label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" id="id_port" name="port">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-2 col-sm-offset-7">
                        <input type="button" class="form-control btn btn-default" value="取消" name="canncl_createProject", onclick="hiddenCreate()">
                    </div>
                    <div class="col-sm-2">
                        <input type="submit" class="form-control btn btn-primary" value="确定" name="submit_createProject">
                    </div>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </div>






    <script>
        function displayCreate() {
            $('#createProject').css({display:'flex'});
        }

        function hiddenCreate() {
            $('#createProject').css({display:'none'});
        }
        function editDate() {
            $('#editbefore').hide();
            $('#editafter').show();
        }

    </script>
{% endblock %}

api/templates/apilist.html
{% extends 'apibase.html' %}


{% block breadcrumb_button %}
    <li><a href="{% url 'api_home' %}">接口平台</a></li>
    <li class="active">{{ project_obj.name }}</li>
    <input class="btn btn-primary btn-xs" type="button" value="添加新接口" style="display: inline;float: right;
    margin-right: 200px" onclick="displayCreate()">
    <input class="btn btn-primary btn-xs" type="button" value="编辑项目" style="float: right; margin-right: 10px" onclick="editDate()">
{% endblock %}



{% block api_home_content %}

<div class="container" id="editbefore">
    <table border="1" class="table table-striped table-bordered table-hover table-condensed table-responsive" >
        <tr>
            <td style="text-align: center">功能</td>
            <td style="text-align: center">接口url</td>
            <td style="width: 80px; text-align: center">请求协议</td>
            <td style="width: 80px; text-align: center">请求方式</td>
            <td style="width: 80px; text-align: center">POST格式</td>
            <td style="width: 80px; text-align: center">作者</td>
            <td style="width: 80px; text-align: center">详情</td>
        </tr>

        {% for form in apiList_formset %}
            <tr>
                <td>{{ form.apiName.value }}</td>
                <td>{{ form.url.value }}</td>
                <td style="min-width: 40px; text-align: center">{{ form.request_protocol.value }}</td>
                <td style="text-align: center">{{ form.request_method.value }}</td>
                <td style="text-align: center">
                    {% ifequal form.post_method.value "x-www-form-urlencoded" %}
                        x-form
                    {% else %}
                        {{ form.post_method.value }}
                    {% endifequal %}
                </td>
                <td style="text-align: center">{{ form.creater.value }}</td>
                <td style="text-align: center">
                    <a href="/api/project{{ project_obj.id }}/api{{  form.id.value  }}/doc">文</a>
                    <a href="/api/project{{ project_obj.id }}/api{{  form.id.value  }}/debug">调</a>
                    <a href="/api/project{{ project_obj.id }}/api{{  form.id.value  }}/test/{{ env_default }}">测</a>
                </td>
            </tr>
        {% endfor %}
    </table>

</div>

<div class="container" id="editafter" style="display: none">
    <form method="post" action="">{% csrf_token %}
    <table border="1" class="table table-striped table-bordered table-hover table-condensed table-responsive" >
        <tr>
            <td style="text-align: center">功能</td>
            <td style="text-align: center">接口url</td>
            <td style="width: 80px; text-align: center">请求协议</td>
            <td style="width: 80px; text-align: center">请求方式</td>
            <td style="width: 80px; text-align: center">POST格式</td>
            <td style="width: 80px; text-align: center">作者</td>
            <td>删除</td>
        </tr>

        {{ apiList_formset.management_form }}
        {% for form in apiList_formset %}

            <tr>
                {{form.id}}
                <td>{{ form.apiName}}</td>
                <td>{{ form.url}}</td>
                <td style="min-width: 40px; text-align: center">{{ form.request_protocol}}</td>
                <td style="text-align: center">{{ form.request_method }}</td>
                <td style="text-align: center">{{ form.post_method}}</td>
                <td style="text-align: center">{{ form.creater}}</td>
                <td>{{  form.DELETE  }}</td>
            </tr>
        {% endfor %}
    </table>
    <input class="btn btn-primary btn-xs" type="submit" value="保存" style="float: right; margin-right: 10px"  name="editsave">
    </form>
</div>

    <div id="createApi" style="width: 100%; height: 100%; background-color: rgba(0,0,0,0.3); position: fixed;
    top: 0; left: 0; display: none; justify-content: center; align-content: center; align-items: center;
    z-index: 9999;">
        <div style="border-radius: 5px; background-color: #fff; max-width: 600px; min-width: 200px; padding: 30px 20px;"
        class="container">
            <form method="post" action="" class="form-horizontal">
                <h3 style="text-align: center">添加新接口</h3>
                <div class="form-group" style="margin-top: 40px">
                    <label class="col-sm-3 control-label">功能:</label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" id="id_apiName" name="apiName">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">url:</label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" id="id_url" name="url">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">请求协议:</label>
                    <div class="col-sm-2">
                        {{ createApi_form.request_protocol }}
                    </div>

                    <label class="col-sm-3 control-label">请求方式:</label>
                    <div class="col-sm-2">
                        {{ createApi_form.request_method }}
                    </div>
                </div>

                <div class="form-group" hidden id="post-method">
                    <label class="col-sm-3 control-label">post方式:</label>
                    <div class="col-sm-5">
                        {{ createApi_form.post_method }}
                    </div>

                </div>

                <div class="form-group">
                    <div class="col-sm-2 col-sm-offset-7">
                        <input type="button" class="form-control btn btn-default" value="取消" name="canncl_createApi" onclick="hiddenCreate()">
                    </div>
                    <div class="col-sm-2">
                        <input type="submit" class="form-control btn btn-primary" value="确定" name="submit_createApi">
                    </div>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </div>
    <script src="{{ STATIC_URL }}js/apilist.js"></script>

{% endblock %}

api/templates/projectconfig.html
{% extends 'apibase.html' %}

{% block breadcrumb_button %}
    <li><a href="{% url 'api_home' %}">接口平台</a></li>
    <li ><a href="/api/project{{ project_obj.id }}">{{ project_obj.name }}</a></li>
    <li class="active">配置页面</li>
{% endblock %}

{% block api_home_content %}

    <div class="container" style="padding-left: 100px">
        <h5>环境配置：</h5>
        <form action="" method="post">
        {{ env_modelformset.management_form }}
        <table border="1" class="table table-striped table-bordered table-hover table-condensed table-responsive" id="env">
            <tr>
                <td style="display: none">projectId</td>
                <td style="text-align: center; width: 15%">环境名</td>
                <td style="text-align: center; width: 30%">host</td>
                <td style="text-align: center; width: 10%">port</td>
                <td style="text-align: center; width: 35%">headers</td>
                <td style="text-align: center; width: 10px">默认</td>
                <td style="text-align: center; width: 10px">删除</td>
            </tr>


            {% for item in env_modelformset %}
                <div style="display: none"> {{ item.id }}</div>
                <tr>
                    <td style="display: none">{{ item.projectId }}</td>
                    <td style="text-align: center; max-width: 100px; min-width: 40px">{{ item.envName }}</td>
                    <td style="text-align: center; max-width: 100px; min-width: 40px">{{ item.envHost }}</td>
                    <td style="text-align: center; max-width: 100px; min-width: 40px">{{ item.envPort }}</td>
                    <td style="text-align: center; max-width: 100px; min-width: 40px">{{ item.envHeaders }}</td>
                    <td style="text-align: center; max-width: 100px; min-width: 40px">{{ item.default }}</td>
                    <td style="text-align: center">{{ item.DELETE }}</td>
                </tr>

            {% endfor %}


        </table>
        <input class="btn btn-danger btn-xs" type="button" value="添加" onclick="addenv()">
        <input class="btn btn-primary btn-xs" type="submit" value="保存" name="saveenv">
        {% csrf_token %}
        </form>
    </div>


<script>
    function addenv(){
        var count = $('#id_form-TOTAL_FORMS').attr("value");
        var smaple_tr1 = $('#env').find('tr');
        var html_tr1 =  smaple_tr1.eq(1).clone(true);
        var form_num =  parseInt(count)+1;


        html_tr1.find('input').each(function () {
            var name = $(this).attr('name');
            var new_name = name.replace(0, form_num-1);
            var id_form = $(this).attr('id');
            var new_id_form = id_form.replace(0, form_num-1);

            $(this).attr('name', new_name);
            $(this).attr('id', new_id_form);
            $(this).attr('value', '');

        }
        );

        html_tr1.find('select').each(function () {
            var name = $(this).attr('name');
            var new_name = name.replace(0, form_num-1);
            var id_form = $(this).attr('id');
            var new_id_form = id_form.replace(0, form_num-1);

            $(this).attr('name', new_name);
            $(this).attr('id', new_id_form);
            $(this).attr('value', '');

        }
        );

        $('#env').append(html_tr1);

        $('#id_form-TOTAL_FORMS').attr("value",parseInt(count)+1);
    }
</script>

{% endblock %}